### ISSUE TITLE
"Start Lisp Instance" not working

### ISSUE THREAD

**Issue by frankiechz** [Enerccio/SLT#74]
Plugin version: 0.5.1

When pressing the "Start Lisp Instance" button I get the following error:

```
java.lang.AssertionError
	at com.en_circle.slt.plugin.SltLibrary.extractAndCopy(SltLibrary.java:42)
	at com.en_circle.slt.plugin.SltLibrary.getSltPath(SltLibrary.java:35)
	at com.en_circle.slt.plugin.SltLibrary.getLibraryInitFile(SltLibrary.java:18)
	at com.en_circle.slt.plugin.environment.SltSBCLEnvironment.prepareProcessEnvironment(SltSBCLEnvironment.java:52)
	at com.en_circle.slt.plugin.environment.SltLispEnvironmentProcess.start(SltLispEnvironmentProcess.java:34)
	at com.en_circle.slt.plugin.services.lisp.LispEnvironmentServiceImpl.doStart(LispEnvironmentServiceImpl.java:185)
	at com.en_circle.slt.plugin.services.lisp.LispEnvironmentServiceImpl.lambda$start$1(LispEnvironmentServiceImpl.java:129)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Enerccio** [comment]
How did you install it?

**Comment by Enerccio** [comment]
Hmm, looks like something went wrong with building the images. Sigh.

**Comment by Enerccio** [comment]
Looks like they changed gradle build to use "instrumented" versions of the build which means my zip task was invoked too late. Making a hotfix and sending it for approval right now. For now you have to downgrade.

**Comment by Enerccio** [comment]
Sorry about this. I released new manual release and sent plugin for reverification. I should have caught that.

**Comment by frankiechz** [comment]
No problem! This project is so impressive! Expect another patron soon.
